version: '3.7'

services:
  #######################################
  # Application
  #######################################
  app:
    build: .
    depends_on:
      - mysql
      - mail
    working_dir: /app
    volumes:
      - ./app/application/:/app/:cached
      - ./docker/nginx.conf:/etc/nginx/conf.d/server.conf
      - ./docker/settings.ini:/etc/php82/conf.d/settings.ini
      - ./docker/xdebug.ini:/etc/php82/conf.d/xdebug.ini
      - ${COMPOSER_CACHE}:/cache/composer:cached
      - ${YARN_CACHE}:/cache/yarn:cached
      - ${NPM_CACHE}:/cache/npm:cached
    ports:
      - 80
    environment:
      - VIRTUAL_HOST=${COMPOSE_PROJECT_NAME}.docker
      - VIRTUAL_PORT=80
    env_file:
      - etc/base.env
      - etc/dev.env

  #######################################
  # MySQL
  #######################################
  mysql:
    image: mariadb:10.3
    ports:
      - 13306:3306
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db:/var/lib/mysql
    env_file:
      - etc/base.env
      - etc/dev.env

  #######################################
  # Mail
  #######################################
  mail:
    image: mailhog/mailhog
    environment:
      - VIRTUAL_HOST=mail.docker
      - VIRTUAL_PORT=8025
    ports:
      - 80

volumes:
  db:
    driver: local

